// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package rootest.org.com.domain;

import org.springframework.beans.factory.annotation.Configurable;
import rootest.org.com.domain.TimerDataOnDemand;

privileged aspect TimerDataOnDemand_Roo_Configurable {
    
    declare @type: TimerDataOnDemand: @Configurable;
    
}
